controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

dashboard:
    path: /template/dashboard/index.html.twig
    defaults: { _controller: 'App\Controller\DashboardController::index' }

session:
    path: /template/session/index.html.twig
    defaults: { _controller: 'App\Controller\SessionController::index' }

app_logout:
    path: /logout

app_obtener_sessions:
    path: /obtener/sessions
    controller: App\Controller\ObtenerSessionsController::getSessions
    methods: ['GET']

app_obtener_events:
    path: /obtener/events
    controller: App\Controller\ObtenerEventsController::getEvents
    methods: ['GET']

app_delete_events:
    path: /delete/evento/{id}
    controller: App\Controller\DeleteEventsController::deleteEvento
    methods: ['DELETE']

app_delete_session:
    path: /delete/session/{id}
    controller: App\Controller\DeleteSessionController::deleteSession
    methods: [ 'DELETE','GET' ]

app_delete_client:
    path: /delete/client/{id}
    controller: App\Controller\DeleteClientController::deleteClient
    methods: [ 'DELETE','GET' ]

app_obtener_services:
    path: /obtener/services/{id}
    controller: App\Controller\ObtenerServicesController::getServices
    methods: ['GET']

app_obtener_all_servicio:
    path: /obtener/services
    controller: App\Controller\ObtenerServicesController::getAllServices
    methods: [ 'GET' ]

app_update_event:
    path: /update/event/{id}
    controller: App\Controller\UpdateEventController::updateEvent
    methods: ['GET']

app_obtener_clients:
    path: /obtener/clients
    controller: App\Controller\ObtenerClientsController::getClients
    methods: [ 'GET' ]

app_session_data:
    path: /session/data
    controller: App\Controller\SessionController::data
    methods: [ 'GET', 'POST' ]

app_albums:
    path: /albums/{id}
    defaults: { _controller: 'App\Controller\AlbumsController::index' }

app_upload_image:
    path: /upload/image
    controller: App\Controller\UploadImageController::uploadImage
    methods: [ 'GET', 'POST' ]

app_save_photos:
    path: /save/photos
    controller: App\Controller\SavePhotosController::savePhotos
    methods: [ 'GET', 'POST' ]

app_obtener_photos:
    path: /obtener/photos
    controller: App\Controller\ObtenerPhotosController::getPhotos
    methods: [ 'GET' ]

app_delete_photos:
    path: /delete/photos/{id}
    controller: App\Controller\DeletePhotosController::deletePhotos
    methods: [ 'DELETE' ]

app_update_photo:
    path: /update/photo/{id}
    controller: App\Controller\UpdatePhotoController::updatePhotos
    methods: [ 'PUT' ]

app_generate_token:
    path: /generate/token
    controller: App\Controller\GenerateTokenController::generateToken
    methods: [ 'POST' ]

app_public_album:
    path: /public/album
    controller: App\Controller\PublicAlbumController::publicAlbum
    methods: [ 'GET' ]

app_obtener_albums:
    path: /obtener/albums
    controller: App\Controller\ObtenerAlbumsController::getAlbums
    methods: [ 'GET' ]

app_update_session:
    path: /update/session
    controller: App\Controller\UpdateSessionController::updateSession
    methods: [ 'GET', 'POST' ]

app_obtener_extras:
    path: /obtener/extras
    controller: App\Controller\ObtenerExtrasController::getExtras
    methods: [ 'GET' ]